# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tsa.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1151, 635)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.tab_3)
        self.widget_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setSpacing(9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.propertiesGroupBox = QtWidgets.QGroupBox(self.widget_2)
        self.propertiesGroupBox.setMaximumSize(QtCore.QSize(16777215, 600000))
        self.propertiesGroupBox.setObjectName("propertiesGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.propertiesGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.propertiesGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.nRowsLabel = QtWidgets.QLabel(self.propertiesGroupBox)
        self.nRowsLabel.setObjectName("nRowsLabel")
        self.gridLayout_2.addWidget(self.nRowsLabel, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.propertiesGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.nColumnsLabel = QtWidgets.QLabel(self.propertiesGroupBox)
        self.nColumnsLabel.setObjectName("nColumnsLabel")
        self.gridLayout_2.addWidget(self.nColumnsLabel, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.propertiesGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.sizeMBLabel = QtWidgets.QLabel(self.propertiesGroupBox)
        self.sizeMBLabel.setObjectName("sizeMBLabel")
        self.gridLayout_2.addWidget(self.sizeMBLabel, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.propertiesGroupBox)
        self.indexGroupBox = QtWidgets.QGroupBox(self.widget_2)
        self.indexGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.indexGroupBox.setObjectName("indexGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.indexGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.setIndexButton = QtWidgets.QPushButton(self.indexGroupBox)
        self.setIndexButton.setObjectName("setIndexButton")
        self.gridLayout.addWidget(self.setIndexButton, 0, 1, 1, 1)
        self.setIndexColumnSelector = QtWidgets.QComboBox(self.indexGroupBox)
        self.setIndexColumnSelector.setObjectName("setIndexColumnSelector")
        self.gridLayout.addWidget(self.setIndexColumnSelector, 0, 0, 1, 1)
        self.resetIndexButton = QtWidgets.QPushButton(self.indexGroupBox)
        self.resetIndexButton.setObjectName("resetIndexButton")
        self.gridLayout.addWidget(self.resetIndexButton, 1, 0, 1, 1)
        self.resetIndexDropButton = QtWidgets.QPushButton(self.indexGroupBox)
        self.resetIndexDropButton.setObjectName("resetIndexDropButton")
        self.gridLayout.addWidget(self.resetIndexDropButton, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.indexGroupBox)
        self.dropColumnsGroupBox = QtWidgets.QGroupBox(self.widget_2)
        self.dropColumnsGroupBox.setMaximumSize(QtCore.QSize(16777215, 600000))
        self.dropColumnsGroupBox.setObjectName("dropColumnsGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dropColumnsGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dropColumnSelector = QtWidgets.QComboBox(self.dropColumnsGroupBox)
        self.dropColumnSelector.setObjectName("dropColumnSelector")
        self.gridLayout_3.addWidget(self.dropColumnSelector, 0, 0, 1, 1)
        self.dropColumnButton = QtWidgets.QPushButton(self.dropColumnsGroupBox)
        self.dropColumnButton.setObjectName("dropColumnButton")
        self.gridLayout_3.addWidget(self.dropColumnButton, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.dropColumnsGroupBox)
        self.modifyColumnsGroupBox = QtWidgets.QGroupBox(self.widget_2)
        self.modifyColumnsGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.modifyColumnsGroupBox.setObjectName("modifyColumnsGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.modifyColumnsGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.modifyTypeColumnSelector = QtWidgets.QComboBox(self.modifyColumnsGroupBox)
        self.modifyTypeColumnSelector.setObjectName("modifyTypeColumnSelector")
        self.gridLayout_4.addWidget(self.modifyTypeColumnSelector, 0, 0, 1, 1)
        self.modifyTypeTypeSelector = QtWidgets.QComboBox(self.modifyColumnsGroupBox)
        self.modifyTypeTypeSelector.setObjectName("modifyTypeTypeSelector")
        self.gridLayout_4.addWidget(self.modifyTypeTypeSelector, 1, 0, 1, 1)
        self.ModifyTypeConfirm = QtWidgets.QPushButton(self.modifyColumnsGroupBox)
        self.ModifyTypeConfirm.setObjectName("ModifyTypeConfirm")
        self.gridLayout_4.addWidget(self.ModifyTypeConfirm, 1, 1, 1, 1)
        self.currentColumnTypeLabel = QtWidgets.QLabel(self.modifyColumnsGroupBox)
        self.currentColumnTypeLabel.setObjectName("currentColumnTypeLabel")
        self.gridLayout_4.addWidget(self.currentColumnTypeLabel, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.modifyColumnsGroupBox)
        self.sortColumnsGroupBox = QtWidgets.QGroupBox(self.widget_2)
        self.sortColumnsGroupBox.setObjectName("sortColumnsGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sortColumnsGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ascendingCheck = QtWidgets.QCheckBox(self.sortColumnsGroupBox)
        self.ascendingCheck.setObjectName("ascendingCheck")
        self.verticalLayout_3.addWidget(self.ascendingCheck)
        self.sortColumnSelector = QtWidgets.QComboBox(self.sortColumnsGroupBox)
        self.sortColumnSelector.setObjectName("sortColumnSelector")
        self.verticalLayout_3.addWidget(self.sortColumnSelector)
        self.sortByIndex = QtWidgets.QPushButton(self.sortColumnsGroupBox)
        self.sortByIndex.setObjectName("sortByIndex")
        self.verticalLayout_3.addWidget(self.sortByIndex)
        self.verticalLayout_4.addWidget(self.sortColumnsGroupBox)
        self.resetGroupBox = QtWidgets.QGroupBox(self.widget_2)
        self.resetGroupBox.setObjectName("resetGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.resetGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.resetDataFrame = QtWidgets.QPushButton(self.resetGroupBox)
        self.resetDataFrame.setObjectName("resetDataFrame")
        self.verticalLayout_5.addWidget(self.resetDataFrame)
        self.verticalLayout_4.addWidget(self.resetGroupBox)
        self.horizontalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignTop)
        self.dfViewGroupBox = QtWidgets.QGroupBox(self.tab_3)
        self.dfViewGroupBox.setObjectName("dfViewGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dfViewGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dataFrameTableView = QtWidgets.QTableView(self.dfViewGroupBox)
        self.dataFrameTableView.setSortingEnabled(True)
        self.dataFrameTableView.setObjectName("dataFrameTableView")
        self.verticalLayout_6.addWidget(self.dataFrameTableView)
        self.horizontalLayout_2.addWidget(self.dfViewGroupBox)
        self.tabWidget.addTab(self.tab_3, "")
        self.decomposition = QtWidgets.QWidget()
        self.decomposition.setObjectName("decomposition")
        self.tabWidget.addTab(self.decomposition, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1151, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.propertiesGroupBox.setTitle(_translate("MainWindow", "Properties"))
        self.label_3.setText(_translate("MainWindow", "N. Rows: "))
        self.nRowsLabel.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "N. Columns:"))
        self.nColumnsLabel.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Size (MB):"))
        self.sizeMBLabel.setText(_translate("MainWindow", "0"))
        self.indexGroupBox.setTitle(_translate("MainWindow", "Index"))
        self.setIndexButton.setText(_translate("MainWindow", "Set Index"))
        self.resetIndexButton.setText(_translate("MainWindow", "Reset Index"))
        self.resetIndexDropButton.setText(_translate("MainWindow", "Reset Idx. Drop"))
        self.dropColumnsGroupBox.setTitle(_translate("MainWindow", "Drop Columns"))
        self.dropColumnButton.setText(_translate("MainWindow", "Drop"))
        self.modifyColumnsGroupBox.setTitle(_translate("MainWindow", "Modify Column Type"))
        self.ModifyTypeConfirm.setText(_translate("MainWindow", "Set Type"))
        self.currentColumnTypeLabel.setText(_translate("MainWindow", "Current Type"))
        self.sortColumnsGroupBox.setTitle(_translate("MainWindow", "Sort "))
        self.ascendingCheck.setText(_translate("MainWindow", "Ascending"))
        self.sortByIndex.setText(_translate("MainWindow", "Sort by Index"))
        self.resetGroupBox.setTitle(_translate("MainWindow", "Reset  (Warning)"))
        self.resetDataFrame.setText(_translate("MainWindow", "Reset"))
        self.dfViewGroupBox.setTitle(_translate("MainWindow", "DataFrame View"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Initialization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.decomposition), _translate("MainWindow", "Seasonal Decomposition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Exploration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Modification"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Modeling"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
